/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EngagementReceptionRouteImport } from './routes/engagement-reception'
import { Route as EditorialFashionRouteImport } from './routes/editorial-fashion'
import { Route as DestinationWeddingsRouteImport } from './routes/destination-weddings'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BridalRouteImport } from './routes/bridal'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademyTwoMonthProfessionalRouteImport } from './routes/academy.two-month-professional'
import { Route as AcademyOneOnOneRouteImport } from './routes/academy.one-on-one'
import { Route as AcademyMasterclassRouteImport } from './routes/academy.masterclass'
import { Route as AcademyLookAndLearnRouteImport } from './routes/academy.look-and-learn'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementReceptionRoute = EngagementReceptionRouteImport.update({
  id: '/engagement-reception',
  path: '/engagement-reception',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialFashionRoute = EditorialFashionRouteImport.update({
  id: '/editorial-fashion',
  path: '/editorial-fashion',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationWeddingsRoute = DestinationWeddingsRouteImport.update({
  id: '/destination-weddings',
  path: '/destination-weddings',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BridalRoute = BridalRouteImport.update({
  id: '/bridal',
  path: '/bridal',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyTwoMonthProfessionalRoute =
  AcademyTwoMonthProfessionalRouteImport.update({
    id: '/two-month-professional',
    path: '/two-month-professional',
    getParentRoute: () => AcademyRoute,
  } as any)
const AcademyOneOnOneRoute = AcademyOneOnOneRouteImport.update({
  id: '/one-on-one',
  path: '/one-on-one',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyMasterclassRoute = AcademyMasterclassRouteImport.update({
  id: '/masterclass',
  path: '/masterclass',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyLookAndLearnRoute = AcademyLookAndLearnRouteImport.update({
  id: '/look-and-learn',
  path: '/look-and-learn',
  getParentRoute: () => AcademyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRouteWithChildren
  '/bridal': typeof BridalRoute
  '/contact': typeof ContactRoute
  '/destination-weddings': typeof DestinationWeddingsRoute
  '/editorial-fashion': typeof EditorialFashionRoute
  '/engagement-reception': typeof EngagementReceptionRoute
  '/faq': typeof FaqRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/academy/look-and-learn': typeof AcademyLookAndLearnRoute
  '/academy/masterclass': typeof AcademyMasterclassRoute
  '/academy/one-on-one': typeof AcademyOneOnOneRoute
  '/academy/two-month-professional': typeof AcademyTwoMonthProfessionalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRouteWithChildren
  '/bridal': typeof BridalRoute
  '/contact': typeof ContactRoute
  '/destination-weddings': typeof DestinationWeddingsRoute
  '/editorial-fashion': typeof EditorialFashionRoute
  '/engagement-reception': typeof EngagementReceptionRoute
  '/faq': typeof FaqRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/academy/look-and-learn': typeof AcademyLookAndLearnRoute
  '/academy/masterclass': typeof AcademyMasterclassRoute
  '/academy/one-on-one': typeof AcademyOneOnOneRoute
  '/academy/two-month-professional': typeof AcademyTwoMonthProfessionalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRouteWithChildren
  '/bridal': typeof BridalRoute
  '/contact': typeof ContactRoute
  '/destination-weddings': typeof DestinationWeddingsRoute
  '/editorial-fashion': typeof EditorialFashionRoute
  '/engagement-reception': typeof EngagementReceptionRoute
  '/faq': typeof FaqRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/academy/look-and-learn': typeof AcademyLookAndLearnRoute
  '/academy/masterclass': typeof AcademyMasterclassRoute
  '/academy/one-on-one': typeof AcademyOneOnOneRoute
  '/academy/two-month-professional': typeof AcademyTwoMonthProfessionalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academy'
    | '/bridal'
    | '/contact'
    | '/destination-weddings'
    | '/editorial-fashion'
    | '/engagement-reception'
    | '/faq'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/thank-you'
    | '/academy/look-and-learn'
    | '/academy/masterclass'
    | '/academy/one-on-one'
    | '/academy/two-month-professional'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academy'
    | '/bridal'
    | '/contact'
    | '/destination-weddings'
    | '/editorial-fashion'
    | '/engagement-reception'
    | '/faq'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/thank-you'
    | '/academy/look-and-learn'
    | '/academy/masterclass'
    | '/academy/one-on-one'
    | '/academy/two-month-professional'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academy'
    | '/bridal'
    | '/contact'
    | '/destination-weddings'
    | '/editorial-fashion'
    | '/engagement-reception'
    | '/faq'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/thank-you'
    | '/academy/look-and-learn'
    | '/academy/masterclass'
    | '/academy/one-on-one'
    | '/academy/two-month-professional'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademyRoute: typeof AcademyRouteWithChildren
  BridalRoute: typeof BridalRoute
  ContactRoute: typeof ContactRoute
  DestinationWeddingsRoute: typeof DestinationWeddingsRoute
  EditorialFashionRoute: typeof EditorialFashionRoute
  EngagementReceptionRoute: typeof EngagementReceptionRoute
  FaqRoute: typeof FaqRoute
  PortfolioRoute: typeof PortfolioRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  ThankYouRoute: typeof ThankYouRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagement-reception': {
      id: '/engagement-reception'
      path: '/engagement-reception'
      fullPath: '/engagement-reception'
      preLoaderRoute: typeof EngagementReceptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-fashion': {
      id: '/editorial-fashion'
      path: '/editorial-fashion'
      fullPath: '/editorial-fashion'
      preLoaderRoute: typeof EditorialFashionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination-weddings': {
      id: '/destination-weddings'
      path: '/destination-weddings'
      fullPath: '/destination-weddings'
      preLoaderRoute: typeof DestinationWeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridal': {
      id: '/bridal'
      path: '/bridal'
      fullPath: '/bridal'
      preLoaderRoute: typeof BridalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/two-month-professional': {
      id: '/academy/two-month-professional'
      path: '/two-month-professional'
      fullPath: '/academy/two-month-professional'
      preLoaderRoute: typeof AcademyTwoMonthProfessionalRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/one-on-one': {
      id: '/academy/one-on-one'
      path: '/one-on-one'
      fullPath: '/academy/one-on-one'
      preLoaderRoute: typeof AcademyOneOnOneRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/masterclass': {
      id: '/academy/masterclass'
      path: '/masterclass'
      fullPath: '/academy/masterclass'
      preLoaderRoute: typeof AcademyMasterclassRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/look-and-learn': {
      id: '/academy/look-and-learn'
      path: '/look-and-learn'
      fullPath: '/academy/look-and-learn'
      preLoaderRoute: typeof AcademyLookAndLearnRouteImport
      parentRoute: typeof AcademyRoute
    }
  }
}

interface AcademyRouteChildren {
  AcademyLookAndLearnRoute: typeof AcademyLookAndLearnRoute
  AcademyMasterclassRoute: typeof AcademyMasterclassRoute
  AcademyOneOnOneRoute: typeof AcademyOneOnOneRoute
  AcademyTwoMonthProfessionalRoute: typeof AcademyTwoMonthProfessionalRoute
}

const AcademyRouteChildren: AcademyRouteChildren = {
  AcademyLookAndLearnRoute: AcademyLookAndLearnRoute,
  AcademyMasterclassRoute: AcademyMasterclassRoute,
  AcademyOneOnOneRoute: AcademyOneOnOneRoute,
  AcademyTwoMonthProfessionalRoute: AcademyTwoMonthProfessionalRoute,
}

const AcademyRouteWithChildren =
  AcademyRoute._addFileChildren(AcademyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademyRoute: AcademyRouteWithChildren,
  BridalRoute: BridalRoute,
  ContactRoute: ContactRoute,
  DestinationWeddingsRoute: DestinationWeddingsRoute,
  EditorialFashionRoute: EditorialFashionRoute,
  EngagementReceptionRoute: EngagementReceptionRoute,
  FaqRoute: FaqRoute,
  PortfolioRoute: PortfolioRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  ThankYouRoute: ThankYouRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
